server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ez-sender
  profiles:
    active: prod
  #jpa & hibernate config
  datasource:
    hikari:
      maximum-pool-size: 40
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      connection-timeout: 30000
      pool-name: EZSenderHikariPoll
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true # set false in production for performance/security
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #mail config
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

#logging
logging:
  level:
    org.springframework: INFO
    org.hibernate: ERROR
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "help,info"
api:
  base:
    path: /${spring.application.name}/api
swagger:
  base:
    path: /${spring.application.name}/swagger
# swagger config
springdoc:
  swagger-ui:
    path: ${swagger.base.path}/api-docs

jwt:
  key: ${JWT_KEY}
  access-token:
    ttl: 1800000 # 30 min
  refresh-token:
    ttl: 604800000 # 7 days